### ISSUE TITLE
Implement rate limiting for tRPC procedures and API routes

### ISSUE THREAD

**Issue by L-Mario564** [Kyoso-Team/kyoso-archive#24]
**Why?**

To lessen the amount of data transferred and processed if any tRPC procedure or API route is abused.

**How?**

Haven't looked much into this myself, suggestions are welcome.

**Comment by kirbytwister** [comment]
Did some research about it, most sources state that it can be done with Redis instance. [Upstash](https://upstash.com/) provides both Redis and API for rate limiting, so we can easily implement it with these two. 

It comes with free plan with daily limit of 10k commands, but if we will encounter traffic increase in the future, we can opt-in for paid plan of (very generous imo) 0.02$ per 100k commands

**Comment by L-Mario564** [comment]
Using Upstash in prod sounds like a good option. For development, you think we can install Redis locally and use that? (I assume yes but asking just in case).

Also, do you want to work on a PR for this issue @ArtemOsuskyi?

**Comment by kirbytwister** [comment]
I'll look into it a bit further, but I guess it anyway requires an Upstash API key to use it.

Also yeah I'm down to work on it
